### ISSUE TITLE
Handshake error

### ISSUE THREAD

**Issue by yuledev** [centrifugal/centrifuge-android#5]
When connect to secure server (wss) i get the error: 
`I/CentrifugoClient: onClose: -1, draft org.java_websocket.drafts.Draft_17@bc1f8b0 refuses handshake, false`.

SSL certificate issue?

**Comment by FZambia** [comment]
Hi, could you try to connect to our public demo wss://centrifugo.herokuapp.com/connection/websocket?

**Comment by yuledev** [comment]
I dont get the reason if i connect to: wss://centrifugo.herokuapp.com/connection/websocket, just this: 
`I/CentrifugoClient: onClose: -1, , true`

**Comment by FZambia** [comment]
We should wait for @SammyVimes to help with this. Maybe this is related to [this issue](https://github.com/TooTallNate/Java-WebSocket/issues/263) so something must be changed in our client core (i.e. using SSLContext when connecting to `wss`).

**Comment by SammyVimes** [comment]
It's a bug, I am not using SSL socket factory for client. Uploading fix to maven

**Comment by SammyVimes** [comment]
@yuledev try version 0.37
`compile 'com.github.centrifugal:centrifuge-android:0.37'`
issue with ssl handshake should be fixed

**Comment by yuledev** [comment]
It is, thanks! :)
