### ISSUE TITLE
can not connect

### ISSUE THREAD

**Issue by hezhubo** [centrifugal/centrifuge-android#6]
After I call `centrifugo.connect();` ,it does not work.And It never call `ConnectionListener` whether the server can not achieve.

**Comment by FZambia** [comment]
@hezhubo hi, do you use Centrifugo v1.6.0? If yes, could you try with v1.5.1?

**Comment by hezhubo** [comment]
Oh,I am sorry.It just my server had not connection call back.It is v1.5.1.However, my web test is OK.

**Comment by FZambia** [comment]
No worries! Btw could you try your setup with v1.6.0? I have no Android experience so can't test this library with new Centrifugo myself.

**Comment by hezhubo** [comment]
Have you ever tested the library? I'm afraid I need to develop according to centrifugo's protocol. That is terrible.  T~T

**Comment by FZambia** [comment]
I am not an author of this lib, it was tested with Centrifugo 1.5.1.

New Centrifugo release has some protocol optimizations, there are no backwards incompatibilities but I think there might be implementation related problems. So to make sure it works I asked you to try it out. If you don't want to help me with this - no problem then.

**Comment by FZambia** [comment]
Opened #7

**Comment by hezhubo** [comment]
I am very happy to do that in my free time. But the first, I need to read the docs, it is too hard to my bad english.

**Comment by hezhubo** [comment]
@FZambia I‘m so sorry about my carelessness. The server url lost '/websocket', so that I can not connect. This library is useful.

**Comment by FZambia** [comment]
Oh, I thought that everything is OK after this comment:
> It just my server had not connection call back.It is v1.5.1.However, my web test is OK.

Looks like I misinterpreted what you meant:)
