### ISSUE TITLE
Test with Centrifugo v1.6.0

### ISSUE THREAD

**Issue by FZambia** [centrifugal/centrifuge-android#7]
We just released Centrifugo v1.6.0 - it has no client protocol backwards incompatible changes, but has some protocol optimizations.

To be more concrete: Centrifugo can return single object response now where it returned array of objects in response to command before. For example in connect response. Client should already handle this as it's a protocol requirement to work both with array and single object responses.

@SammyVimes could you test it with Centrifugo v1.6.0? Hopefully it will just work. I can not do this myself unfortunately as I am too far from Android world.

**Comment by FZambia** [comment]
@SammyVimes ping

**Comment by SammyVimes** [comment]
Tested. It's safe to say, library is still relevant
